### ISSUE TITLE
Daily Missions: Property Visits don't track.

### ISSUE THREAD

**Issue by NealSpellman** [DarkflameUniverse/DarkflameBugTracker#1]
Visiting properties while doing the daily mission for visiting properties never progresses.

Steps to Reproduce:
1. Grab the daily visit properties mission at the launch area in Avant Gardens.
2. Fly to another player's property.
3. Notice that progress is not incremented.

**Comment by Wincent01** [comment]
Tracking for this task type added with [this](https://github.com/DarkflameUniverse/DLUv3/commit/0ddc4aeedbedf434a20ee442d8c8fc38f22b3886) commit.
