### ISSUE TITLE
Return to Venture Explorer: Mechs don't drop quickbuilds.

### ISSUE THREAD

**Issue by NealSpellman** [DarkflameUniverse/DarkflameBugTracker#18]
The [Corrupted Sentry](https://lu-explorer.web.app/objects/8433) does not drop a quickbuild like it should. See [this video](https://youtu.be/k-Cv6zg2pgk?t=67) for intended behavior from Live.

Steps to Reproduce:
1. Head to Return to the Venture Explorer.
2. Smash a Corrupted Sentry.
3. Notice no quickbuild drops.

**Comment by MickVermeulen** [comment]
fixed in latest patch
