### ISSUE TITLE
"A Feat of Imagination" not progressing from Imagination Brick collection

### ISSUE THREAD

**Issue by NealSpellman** [DarkflameUniverse/DarkflameBugTracker#27]
Testers noted the Avant Gardens Imagination Brick and the Nexus Tower Imagination Brick both did not count for this achievement.

Steps to Reproduce:
1. Create a new character.
2. Attempt to collect either AG or NT's Imagination Brick.
3. Notice that no progress has been made on "A Feat of Imagination".

**Comment by MickVermeulen** [comment]
I was not able to reproduce this issue, both the AG and NT imagination bricks progressed this achievement for me

**Comment by NealSpellman** [comment]
Think we can close this now then.
