### ISSUE TITLE
Daily Missions: Players can infinitely accept and reroll dailies

### ISSUE THREAD

**Issue by NealSpellman** [DarkflameUniverse/DarkflameBugTracker#34]
Currently, there is no cap for dailies and players can infinitely do them + reroll them.

From a tester:
"There is that bug where you can do as many dailies as you want in a day. On Crux (might be applicable elsewhere), if you only do the same daily mission in a row, that being if you decline the other missions until you can accept the same mission you had last time. That mission will not track progress but will be instantly completed if you log out or switch mini-figures back in. If you continue to do that same mission, it will never track until you accept a different version of the daily mission and then they will reset and start tracking again."

Players should not be able to infinitely do daily missions.

Steps to Reproduce:
1. Visit an NPC that has multiple daily missions.
2. Grab one and complete it.
3. Return and keep rerolling by declining and talking to the NPC until you get the same one.
4. Log out or switch minifigures.
5. Log back in and notice the mission is complete.
6. Start the process again with finding the same daily again.

**Comment by MickVermeulen** [comment]
Fixed with the most recent patch
