### ISSUE TITLE
Avant Gardens: Wisp Lee won't complete Hu Where's daily instead of completing FV visit quest

### ISSUE THREAD

**Issue by MickVermeulen** [DarkflameUniverse/DarkflameBugTracker#46]
Instead of being able to complete the go to wisp lee mission from VE, some testers are experiencing a bug where instead they're offered the maelstrom vacuum mission.

**Comment by MickVermeulen** [comment]
Bug report was a bit misformulated, it was actually the go to Wisp Lee daily.

**Comment by NealSpellman** [comment]
> Bug report was a bit misformulated, it was actually the go to Wisp Lee daily.

Still the wrong case; they're in the middle of the [FV mission to return to Wisp Lee](https://lu-explorer.web.app/missions/736) and are trying to go complete it, but Wisp is offering his Maelstrom Vacuum daily.

**Comment by MickVermeulen** [comment]
Thanks for clarifying!

**Comment by MickVermeulen** [comment]
It seems like under those exact circumstances I'm not able to replicate this issue, for me it offers both the option to accept the daily and the option to complete mission 736. I tried this with both having the daily active and available.

**Comment by NealSpellman** [comment]
Looks like I was wrong and no one explained it properly in the bug reports until now; there's another daily that interacts with Wisp Lee, one from Hu Where, that causes this issue.

**Comment by MickVermeulen** [comment]
Fixed in the latest release
