### ISSUE TITLE
Avant Gardens: Monument Maintenance achievement isn't tracked

### ISSUE THREAD

**Issue by NealSpellman** [DarkflameUniverse/DarkflameBugTracker#7]
Buttons, bouncers and moving platforms don't count for this achievement when they should.

Steps to Reproduce:
1. Visit the Monument and quickbuild the objects noted above.
2. Notice that the achievement does not track progress.

**Comment by MickVermeulen** [comment]
Should have been fixed when I completed all the achievements in AG, worth a quick check in game but should be resolved.

**Comment by MickVermeulen** [comment]
yup, this tracks!
